### PR TITLE
Add aggregate data sharing resource

### PR DESCRIPTION
**Pull request by liberaliscomputing**
This PR adds the aggregate data sharing resource.  The followings are to be discussed/implemented:

- Reading in the following credentials from environment variables at `AggregateDataSharingResource.java` is not secure since the Docker engine logs all environment variables. Consider adding
them as naming entries in the `standalone.xml` and load in a different way:

```java
private static final String TARGET_PICSURE_URL = System.getenv("TARGET_PICSURE_URL");
private static final String TARGET_PICSURE_TOKEN = System.getenv("TARGET_PICSURE_TOKEN");
```
- Re `// obfuscate value here` at `AggregateDataSharingResource.java`, I looked into the web developer console to explore requests and responses for the PIC-SURE UI. I found a response payload carries only a stringified integer (not in a JSON format) when  query is done. Am I grabbing this and comparing to `TARGET_AGGREGATE_PICSURE_THRESHOLD`?

### CODE REVIEW

**Comment by liberaliscomputing** [comment]
Re importing credentials, Nate recommended to use the `@Resource` annotation at `AggregateDataSharingResource.java` as follows:

```java
@Resource(mappedName = "java:global/__TARGET_AGGREGATE_PICSURE_URL__")
public static String TARGET_AGGREGATE_PICSURE_URL;
@Resource(mappedName = "java:global/__TARGET_AGGREGATE_PICSURE_TOKEN__")
public static String TARGET_AGGREGATE_PICSURE_TOKEN;
```

The above change has been made.

**Comment by liberaliscomputing** [comment]
During the call on 10-14-2020, the followings were discussed:

- Re importing credentials, rename the imported variables, using camel-casing
- Re obfuscation, grab the initial response, type-cast to an integer, compare with the threshold, and return a stringified integer or obfuscation message

The above changes have been made.

**Comment by liberaliscomputing** [comment]
The properties import has been refactored against the followings:

- https://github.com/nixj14/pic-sure/blob/GIC_aggregate_resource/pic-sure-resources/pic-sure-passthrough-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/passthru/ApplicationProperties.java
- https://github.com/nixj14/pic-sure/blob/GIC_aggregate_resource/pic-sure-resources/pic-sure-passthrough-resource/src/main/java/edu/harvard/hms/dbmi/avillach/resource/passthru/JAXRSConfiguration.java

**Review by chunacatsunflower — APPROVED** [review]
Looks good!  Thanks.

**Pull request merged**
